### ISSUE TITLE
Accuracy Results Meaning?

### ISSUE THREAD

**Issue by GrayGriffin** [SamsungLabs/eagle#10]
I've been working with the predictor for a while, and something I've realized is that I'm not quite sure what the ±0.1,0.01,etc. accuracy results mean in the final log. I know about top-1 accuracy in CIFAR10/100, but I'm not sure what the ± part is supposed to symbolize here. I looked at the corresponding paper, but it doesn't seem to describe the results in these terms.

**Comment by thomasccp** [comment]
The numbers in ±[0.01, 0.05, 0.1, 0.2] mean the percentage of predictions that are within ±[1%, 5%, 10%, 20%] of the ground truths. For example, 90% of ±0.01 means that 90% of predicted values are within ±1% error wrt the ground truth.

**Comment by GrayGriffin** [comment]
How does that work with CIFAR10/100 though? Since the ground truth for those datasets can't really be represented in a percentage form.

**Comment by thomasccp** [comment]
Let's say the ground truth top-1 accuracy of model A in CIFAR100 is 80%, then if the prediction is between 79.2% and 80.8%, we can say it is within the bound of  ±0.01.
If 90% of models fit the above criteria, then we say 90% prediction are within ±0.01.
