### ISSUE TITLE
Is the dataset in google drive still available?

### ISSUE THREAD

**Issue by SakuraiYuuta** [SamsungLabs/eagle#15]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/52504781/234072609-ac8a5af9-1aa9-4fd8-9543-f6b161a900ca.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/52504781/234072674-be600f71-ae39-452e-82ea-7fe429dfe8f9.png">

I didn't find the pickle files in the google drive, instead, i only found xlsx files in the Hist_Barchart_Data folder

**Comment by vaenyr** [comment]
Hi, thanks for bringing this to our attention. We don't know what happened - the folder you mention has neither been created nor put in our shared drive by us... Fortunately we should still have the source files stored locally so I should be able to reupload them (will try to do this tomorrow). We will also have to double check what happened with the shared folder and maybe find a new home for the files... but that's another discussion.

Once again thanks for pointing this out, and apologies for any troubles.

**Comment by SakuraiYuuta** [comment]
> dn't find the pickle files in
Thank you so much for your help!

**Comment by SakuraiYuuta** [comment]
> Once again thanks for pointing this out

Thank you for responding!

**Comment by vaenyr** [comment]
Hi, we've reuploaded the files - if anything is missing, let us know!

**Comment by SakuraiYuuta** [comment]
Thank you so much for your help!
