### ISSUE TITLE
Is accuracy dataset uploaded?

### ISSUE THREAD

**Issue by SakuraiYuuta** [SamsungLabs/eagle#16]
Hi, I didn't find accuracy dataset, seems the Google Drive link only contains latency dataset.

**Comment by vaenyr** [comment]
Sorry for that, I must have forgotten to reupload them.
I'm currently on holidays without access to the data so will only be able to put the files in the gdrive on Wednesday (03 May). Let me know if you need the files urgently, I might be able to find someone else to handle it for me, though. Also, if you have access to the original dataset, generating those files yourself should be fairly simple!

**Comment by SakuraiYuuta** [comment]
> generating those files yourself should be fairly simple!

Thank you! I have tried to generate those files by myself, but seems the prediction results are not so great comparing to the results in paper. Just want to check why I can't reproduce the results, but it's not urgent, whenever you are not busy!

**Comment by thomas-neubla** [comment]
> > generating those files yourself should be fairly simple!
> 
> Thank you! I have tried to generate those files by myself, but seems the prediction results are not so great comparing to the results in paper. Just want to check why I can't reproduce the results, but it's not urgent, whenever you are not busy!

I have uploaded the accuracy files to gdrive. You may try them. Thanks!

**Comment by SakuraiYuuta** [comment]
> I have uploaded the accuracy files to gdrive. You may try them. Thanks!

Thank you so much!

**Comment by SakuraiYuuta** [comment]
Seems that different pip install nas-bench-201 version will trigger different reading results, and that's the reason I got wrong accuracy dataset.

**Comment by SakuraiYuuta** [comment]
Seem that different pip install nas-bench-201 version will trigger different reading results of the pth files they provided, I guess that's why I got the wrong accuracy dataset by myself.
