### ISSUE TITLE
pip install eagle: python3 or python2?

### ISSUE THREAD

**Issue by YingYuChen97** [SamsungLabs/eagle#8]
I've got logs below while installing eagle:

```
$ pip install eagle
Collecting eagle
  Using cached eagle-0.2.tar.gz (417 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/andy/anaconda3/envs/pytorch/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vw3svb83/eagle_ca7b4cba24b942c19a8c35b503fdfc19/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vw3svb83/eagle_ca7b4cba24b942c19a8c35b503fdfc19/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_uca8aqj
         cwd: /tmp/pip-install-vw3svb83/eagle_ca7b4cba24b942c19a8c35b503fdfc19/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vw3svb83/eagle_ca7b4cba24b942c19a8c35b503fdfc19/setup.py", line 3, in <module>
        import ez_setup
      File "/tmp/pip-install-vw3svb83/eagle_ca7b4cba24b942c19a8c35b503fdfc19/ez_setup/__init__.py", line 176
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/dd/5c/4318a37b78339ab35e8340d51ddcb76f8005261dffcd5d1e9ab7cec0b5cd/eagle-0.2.tar.gz#sha256=7af5dffd0f1f2b5c46dcc19f5b5a47e96dc3ce387f1de05199df249e8d2bed59 (from https://pypi.org/simple/eagle/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement eagle (from versions: 0.2)
ERROR: No matching distribution found for eagle

```

It shows that there's a print syntax error in ***__init__.py line 176***
The syntax of **print  "Setuptools version",version,"or greater has been installed."** is compatible for python2 but not python3.
Please help to download the package.

**Comment by YingYuChen97** [comment]
```
git clone https://github.com/SamsungLabs/eagle
```
an **eagle** folder created, then 
```
pip install eagle
```
doesn't work, still show the same log like above.

**Comment by YingYuChen97** [comment]
``` pip install eagle-main.zip ```

**Successfully installed Eagle-1.1.0 astunparse-1.6.3 cachetools-4.2.4 charset-normalizer-2.0.7 clang-5.0 flatbuffers-1.12 gast-0.4.0 google-auth-2.3.2 google-auth-oauthlib-0.4.6 idna-3.3 keras-2.6.0 oauthlib-3.1.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyyaml-6.0 requests-2.26.0 requests-oauthlib-1.3.0 rsa-4.7.2 six-1.15.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.6.0 tensorflow-estimator-2.7.0 tqdm-4.62.3 typing-extensions-3.7.4.3 urllib3-1.26.7 wrapt-1.12.1**

It works but the default Tensorflow version is the latest version instead of you requirement(>=1.13,<2)
Will have to uninstall Tensorflow and reinstall.

**Comment by vaenyr** [comment]
Yes, sorry for that. We actually have a fix for TF>2 waiting to be pushed to this repo. Maybe some time soon I'll find some time to do that.
Anyway, since the problem seem to have been resolved I'm closing the issue. Feel free to reopen if needed.
