### ISSUE TITLE
ModuleNotFoundError: No module named 'eagle'

### ISSUE THREAD

**Issue by GrayGriffin** [SamsungLabs/eagle#9]
I'm getting this error when I try to run results_calc.py on the combined pickle dataset. Not sure why it's happening now since I was able to run it before.

**Comment by vaenyr** [comment]
Make sure our package is installed.
We recommend in-place installation with:
`python -m pip install -e <path_to_repo>`

Bear in mind that different python installations do not share their packages, e.g. if python got upgraded it might now use a version for which eagle hasn't been installed. The same goes for all virtual environments etc.

In general, python documentation is a good starting point in case of some unusually tricky problems: https://docs.python.org/3/reference/import.html
